name: flutter_grocery
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+4

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  cupertino_icons: ^1.0.8
  get_it: ^7.7.0
  provider: ^6.1.2
  http: ^0.13.6
  shared_preferences: ^2.2.3
  photo_view: ^0.15.0
  dio: ^5.4.3+1
  image_picker: ^1.1.2
  pin_code_fields: ^8.0.1
  google_maps_flutter_web: ^0.5.6+2
  google_maps_flutter: ^2.6.1
  flutter_google_places: ^0.3.0
  geocoding: ^3.0.0
  geolocator: ^11.0.0
  shimmer_animation: ^2.1.0+1
  url_launcher: ^6.3.1
  firebase_core: ^2.30.0
  firebase_messaging: ^14.8.2
  flutter_local_notifications: ^17.1.0
  path_provider: ^2.1.3
  connectivity: ^3.0.6
  carousel_slider: ^5.0.0
  fluro: ^2.0.5
  url_strategy: ^0.2.0
  universal_html: ^2.2.4
  flutter_widget_from_html_core: ^0.14.11
#  phone_number: ^2.1.0
  country_code_picker: ^3.0.0
  flutter_typeahead: ^5.2.0
  cached_network_image: ^3.3.1
  audioplayers: ^6.0.0
  flutter_facebook_auth: ^6.0.4
  google_sign_in: ^6.2.1
  expandable_bottom_sheet: ^1.1.1+1
  dotted_border: ^2.1.0
  share_plus: ^9.0.0
  scroll_to_index: ^3.0.1
  simple_speed_dial: ^0.1.7
#  firebase_auth: ^4.19.3
  flutter_svg: ^2.0.9
  flutter_xlider: ^3.5.0
#  firebase_crashlytics: ^3.5.3
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.13.1
  google_fonts: ^4.0.4

  google_maps_webservice: any
  collection: any
  flutter_animate: ^4.5.0
  font_awesome_flutter: ^10.8.0
  webview_flutter: ^4.8.0
#  webview_flutter_android: ^3.16.8
  image: ^4.3.0
  flutter_image_compress: ^2.3.0
#  flutter_inappwebview: ^5.8.0
# flutter_native_splash:
#   color: "#FFFFFF"
#   image: assets/image/splash.png
#   android_12:
#     image: assets/image/android_12_splash.png
#   android: true
#   ios: true

##flutter_launcher_icons:
##  android: "launcher_icon"
##  ios: true
##  image_path: "assets/image/app_logo.JPG"
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/keakado_app_logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2


flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/svg/
    - assets/language/
    - assets/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Light.ttf
          weight: 300
        - asset: assets/font/Poppins-Regular.ttf
          weight: 400
        - asset: assets/font/Poppins-Medium.ttf
          weight: 500
        - asset: assets/font/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/font/Poppins-Bold.ttf
          weight: 700
    - family: NunitoSans
      fonts:
        - asset: assets/font/NunitoSans-Light.ttf
          weight: 300
        - asset: assets/font/NunitoSans-Regular.ttf
          weight: 400
        - asset: assets/font/NunitoSans-Medium.ttf
          weight: 500
        - asset: assets/font/NunitoSans-SemiBold.ttf
          weight: 600
        - asset: assets/font/NunitoSans-Bold.ttf
          weight: 700
    